


development:
  adapter: postgresql
  encoding: unicode
  database: fake_twitter_development
  pool: 5
  username: 
  password: 
  timeout: 5000
 

test:
  adapter: postgresql
  encoding: unicode
  database: fake_twitter_test
  pool: 5
  username: 
  password: 
  timeout: 5000

production:
  <<: *default
  database: fake_twitter_production
  username: 
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>