


development:
  adapter: postgresql
  encoding: unicode
  database: fake_twitter_development
  pool: 5
  username: conorcurran
  password: 
  timeout: 5000
 

test:
  adapter: postgresql
  encoding: unicode
  database: fake_twitter_test
  pool: 5
  username: conorcurran
  password: 
  timeout: 5000


